# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scaleC <- function(X) {
    .Call('_APML0_scaleC', PACKAGE = 'APML0', X)
}

OmegaC <- function(Omega, sgn) {
    .Call('_APML0_OmegaC', PACKAGE = 'APML0', Omega, sgn)
}

OmegaSC <- function(OmegaS, sgn) {
    .Call('_APML0_OmegaSC', PACKAGE = 'APML0', OmegaS, sgn)
}

maxLambdaLmC <- function(X, y, alpha, wbeta, N0, p) {
    .Call('_APML0_maxLambdaLmC', PACKAGE = 'APML0', X, y, alpha, wbeta, N0, p)
}

cvTrimLmC <- function(beta, nn, nn2, loco, XF, yF, NF, a0) {
    .Call('_APML0_cvTrimLmC', PACKAGE = 'APML0', beta, nn, nn2, loco, XF, yF, NF, a0)
}

EnetLmC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, p, N0, thresh, maxit, thresh2) {
    .Call('_APML0_EnetLmC', PACKAGE = 'APML0', X, y, alpha, lambda, nlambda, ilambda, wbeta, p, N0, thresh, maxit, thresh2)
}

cvEnetLmC <- function(X, y, alpha, lambda, nlambda, wbeta, N, p, thresh, maxit, XF, yF, NF, thresh2) {
    .Call('_APML0_cvEnetLmC', PACKAGE = 'APML0', X, y, alpha, lambda, nlambda, wbeta, N, p, thresh, maxit, XF, yF, NF, thresh2)
}

NetLmC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, Omega, loc, nadj, p, N0, thresh, maxit, thresh2) {
    .Call('_APML0_NetLmC', PACKAGE = 'APML0', X, y, alpha, lambda, nlambda, ilambda, wbeta, Omega, loc, nadj, p, N0, thresh, maxit, thresh2)
}

cvNetLmC <- function(X, y, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, p, thresh, maxit, XF, yF, NF, thresh2) {
    .Call('_APML0_cvNetLmC', PACKAGE = 'APML0', X, y, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, p, thresh, maxit, XF, yF, NF, thresh2)
}

maxLambdaCoxC <- function(X, tevent, N, nevent, nevent1, loc1, n, alpha, wbeta, N0, p) {
    .Call('_APML0_maxLambdaCoxC', PACKAGE = 'APML0', X, tevent, N, nevent, nevent1, loc1, n, alpha, wbeta, N0, p)
}

pletaCm <- function(xb, exb, nevent, nevent1, loc1, n, ifast, itwo) {
    .Call('_APML0_pletaCm', PACKAGE = 'APML0', xb, exb, nevent, nevent1, loc1, n, ifast, itwo)
}

cvTrimCoxC <- function(beta, nn, nn2, loco, XF, NF, neventF, nevent1F, loc1F, nF, X, N, nevent, nevent1, loc1, n, ifast, itwo) {
    .Call('_APML0_cvTrimCoxC', PACKAGE = 'APML0', beta, nn, nn2, loco, XF, NF, neventF, nevent1F, loc1F, nF, X, N, nevent, nevent1, loc1, n, ifast, itwo)
}

EnetCoxC <- function(X, tevent, alpha, lambda, nlambda, ilambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast) {
    .Call('_APML0_EnetCoxC', PACKAGE = 'APML0', X, tevent, alpha, lambda, nlambda, ilambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast)
}

cvEnetCoxC <- function(X, tevent, alpha, lambda, nlambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF) {
    .Call('_APML0_cvEnetCoxC', PACKAGE = 'APML0', X, tevent, alpha, lambda, nlambda, wbeta, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF)
}

NetCoxC <- function(X, tevent, alpha, lambda, nlambda, ilambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast) {
    .Call('_APML0_NetCoxC', PACKAGE = 'APML0', X, tevent, alpha, lambda, nlambda, ilambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast)
}

cvNetCoxC <- function(X, tevent, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF) {
    .Call('_APML0_cvNetCoxC', PACKAGE = 'APML0', X, tevent, alpha, lambda, nlambda, wbeta, Omega, loc, nadj, N, nevent, nevent1, loc1, n, p, N0, thresh, maxit, ifast, XF, NF, neventF, nevent1F, loc1F, nF)
}

maxLambdaLogC <- function(X, Z, alpha, wbeta, N0, p) {
    .Call('_APML0_maxLambdaLogC', PACKAGE = 'APML0', X, Z, alpha, wbeta, N0, p)
}

cvTrimLogC <- function(beta, nn, nn2, loco, XF, yF, NF, threshP) {
    .Call('_APML0_cvTrimLogC', PACKAGE = 'APML0', beta, nn, nn2, loco, XF, yF, NF, threshP)
}

EnetLogC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, p, N0, thresh, maxit, threshP) {
    .Call('_APML0_EnetLogC', PACKAGE = 'APML0', X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, p, N0, thresh, maxit, threshP)
}

cvEnetLogC <- function(X, y, alpha, lambda, nlambda, wbeta, wbetai, p, N0, thresh, maxit, XF, yF, NF, threshP) {
    .Call('_APML0_cvEnetLogC', PACKAGE = 'APML0', X, y, alpha, lambda, nlambda, wbeta, wbetai, p, N0, thresh, maxit, XF, yF, NF, threshP)
}

NetLogC <- function(X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, threshP) {
    .Call('_APML0_NetLogC', PACKAGE = 'APML0', X, y, alpha, lambda, nlambda, ilambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, threshP)
}

cvNetLogC <- function(X, y, alpha, lambda, nlambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, XF, yF, NF, threshP) {
    .Call('_APML0_cvNetLogC', PACKAGE = 'APML0', X, y, alpha, lambda, nlambda, wbeta, wbetai, Omega, loc, nadj, p, N0, thresh, maxit, XF, yF, NF, threshP)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_APML0_RcppExport_registerCCallable', PACKAGE = 'APML0')
})
